'c'
'open data_2016'
'set lat -90 90'
'set lev 1000 10'
'set lon 180'
'set t 6'
'set gxout shaded'
'd ave(ave(Qprs,lon=0,lon=360),t=1,t=12)'
'draw title Annual_zonal_averaged_sp_humidity'
'draw xlab latitude'
'draw ylab pressure'
'gxprint humidity.png'
