'c'
'open fnl_060903_00_00.ctl'
'set lev 1000 10'
'set lat 0'
'set lon 90'
'myvar = ave(ave(tmpprs,lat=-90,lat=90),lon=0,lon=360)'
'd myvar'
'draw xlab Temperature (K)'
'draw ylab Pressure axis (hPa)'
'draw title Global average temperature profile'
'gxprint temp_profile.png'
